[General]
GeoLocale=system
SensitiveInfoMaskOn=true
ShowBiDirecSyncNoti=true
autoPlayGif=false
autoScale=true
bForceMaximizeWM=false
captureHDCamera=true
cefInstanceCountLimit=-1
cefRefreshTime=0
cefhttpProxyHost=127.0.0.1
cefhttpProxyPort=7890
cefhttpsProxyHost=127.0.0.1
cefhttpsProxyPort=7890
cefpacFilePath=
cefproxyType=noproxy
chatListPanelLastWidth=320
com.zoom.client.langid=0
com.zoom.pt.settings.closedcaption.fontsize=16
conf.webserver=https://us05web.zoom.us
conf.webserver.vendor.default=https://zoom.us
currentMeetingId=
deviceID=08:5B:D6:CB:0E:DF
disableCef=false
disableUsePasskey=false
enable.host.auto.grab=true
enableAlphaBuffer=false
enableCefGpu=false
enableCefLog=false
enableCefOsrMode=true
enableCefTa=false
enableCloudSwitch=true
enableLog=true
enableMiniWindow=false
enableQmlCache=true
enableScreenSaveGuard=false
enableStartMeetingWithRoomSystem=false
enableTestMode=false
enableUnifywebviewTa=false
enableWaylandShare=false
enablegpucomputeutilization=false
fake.version=
flashChatTime=0
forceEnableTrayIcon=true
forceSSOURL=
hideCrashReport=false
host.auto.grab.interval=10
httpProxyHost=127.0.0.1
httpProxyPort=7890
httpsProxyHost=127.0.0.1
httpsProxyPort=7890
isTransCoding=false
legacyAvatarCacheCleaned=1777074866
logLevel=info
newMeetingWithVideo=true
noSandbox=false
pacFilePath=
playSoundForNewMessage=false
proxyType=noproxy
scaleFactor=1
shareBarTopMargin=0
shortcut_as_global_ShortcutID_Screenshot=false
shortcut_as_global_ShortcutID_ShowHideFloatingMeetingControls=true
showOneTimePTAICTipHubble=false
showOneTimeQueriesOptionTip=true
showOneTimeSmartRecognitionCoackMark=true
showOneTimeTranslationUpSellTip=false
showSystemTitlebar=false
speaker_volume=255
sso_domain=.zoom.us
sso_gov_domain=.zoomgov.com
system.audio.type=default
systemDockMargin=0
timeFormat12HoursEnable=true
translationFreeTrialTipShowTime=0
upcoming_meeting_header_image=
useSystemTheme=false
userEmailAddress=hl.jiang_@outlook.com
webview.debug.enable=false
xwayland=true

[AS]
showframewindow=true

[chat.recent]
recentlast.session=

[zoom_new_im]
is_landscape_mode=true
main_frame_pixel_pos_narrow="376,600"
main_frame_pixel_pos_wide="1280,960"
